  on: [push]
  jobs:
    build:
      name: build
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup JDK
          uses: actions/setup-java@v2
          with:
            java-version: '19'
            distribution: 'adopt'

        - name: Build Project
          run: mvn compile

        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: artifacts
            path: target
    test:
      name: test
      needs: [build]
      runs-on: self-hosted
      steps:
        - name: Setup JDK
          uses: actions/setup-java@v2
          with:
            java-version: '19'
            distribution: 'adopt'
            
        - name: Download Artifacts
          uses: action/download-artifact@v2
          with:
            name: artifacts

        - name: test
          run: mvn test





